### ISSUE TITLE
Not correctly detecting Mac platform

### ISSUE THREAD

**Issue by paulgittings** [andycb/PiSharp#3]
LibGpio.GetGpioPath() is not picking up that the code is running on a Mac.  The issue seems to be that the Environment.OSVersion.Platform is not returning PlatformID.MacOSX but is instead returning PlatformID.Unix.

Need to also check for PlatformID.Unix

See discussion here http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform

**Comment by andycb** [comment]
Thanks for the detailed info. I've updated as per your link.

Andy
